### ISSUE TITLE
Values Don't Populate In Selected Cell

### ISSUE THREAD

**Issue by angieandera** [joaomelo/blog-dialog-to-select-multiple-values-in-google-sheets#1]
Is there a way to hide the red error indicator flags in the corners of all of the cells that have multiple values? Or else a way to ignore having to check the "show warning" option when creating the data validation?

![Screen Shot 2020-06-10 at 6 35 20 PM](https://user-images.githubusercontent.com/66750507/84329035-3649f400-ab49-11ea-98f2-e305b4954b72.jpg)

**Comment by joaomelo** [comment]
Please, check the validation data dialog for the cells, and make sure the "On invalid data:" option is set to "show warning" and not "reject input".

**Comment by joaomelo** [comment]
Please, check the validation data dialog for the cells, and make sure the "On invalid data:" option is set to "show warning" and not "reject input".

**Comment by joaomelo** [comment]
The validation data setup is used to create the dialog with the options, but it is, in reality, a hack. When the script fills the cell with multiple values it for all reasons break the validation rule. So, for this script, there is no way.

One could, however, work the script to pull data from another source dispensing the validation setup. Like a fixed set of cells.

**Comment by joaomelo** [comment]
The getOptionsFromCurrentCell function will be the target for change. Specifically this instruction:

```
  const validOptions = SpreadsheetApp
    .getActiveRange() // everything that is selected
    .getDataValidation() // all validation rules for that
    .getCriteriaValues()[0] // the first criteria
    .getValues() // the value for this criteria
    .map(value => value[0]); // flatten in an one dimension array

```
